package io.github.iamfacetheflames.rangpur.core.model.sync

const val PORT: Int = 54286

object Command {
    const val START_SYNC = "COMMAND_START_SYNC"
    const val REQUEST_DIRECTORIES = "COMMAND_REQUEST_DIRECTORIES"
    const val SEND_DIRECTORIES = "COMMAND_SEND_DIRECTORIES"
    const val REQUEST_AUDIOS = "COMMAND_REQUEST_AUDIOS"
    const val SEND_AUDIO = "COMMAND_SEND_AUDIO"
    const val REQUEST_PLAYLIST_FOLDERS = "COMMAND_REQUEST_PLAYLIST_FOLDERS"
    const val SEND_PLAYLIST_FOLDERS = "COMMAND_SEND_PLAYLIST_FOLDERS"
    const val REQUEST_PLAYLISTS = "COMMAND_REQUEST_PLAYLISTS"
    const val SEND_PLAYLISTS = "COMMAND_SEND_PLAYLISTS"
    const val REQUEST_PLAYLIST_AUDIOS = "COMMAND_REQUEST_PLAYLIST_AUDIOS"
    const val SEND_PLAYLIST_AUDIOS = "COMMAND_SEND_PLAYLIST_AUDIOS"
    const val NEW_AUDIOS_AMOUNT = "COMMAND_NEW_AUDIOS_AMOUNT"
    const val DONE = "COMMAND_DONE"
    const val ERROR = "COMMAND_ERROR"
}